apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-service
  ports:
  - port: {{ .Values.app.servicePort }}
    targetPort: {{ .Values.app.containerPort }}
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model-service
  ports:
  - port: {{ .Values.model.servicePort }}
    targetPort: {{ .Values.model.containerPort }}
    protocol: TCP
  type: ClusterIP